name: Build AVDVPlus CoreELEC

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360 # 360分钟超时，防止编译中途被砍

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git build-essential bc libncurses5-dev libssl-dev \
            flex bison gperf python3 python3-pip python3-setuptools \
            zip unzip wget curl rsync ccache

      # 🔥 重点：删除了创建16G Swap的步骤，因为Actions环境不需要
      - name: Build CoreELEC Image
        run: |
          export USE_CCACHE=1
          export CCACHE_DIR=/tmp/ccache
          ccache -M 30G # 设置缓存大小
          make -j4 image # 编译并生成tar包

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: CoreELEC-AVDVPlus-Firmware
          path: target/* # 上传target下所有文件（包含tar和img）
          retention-days: 7 # 保留7天
