name: Build AVDVPlus CoreELEC

on:
  workflow_dispatch:  # 手动触发编译
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 420  # 最大7小时，足够完整编译

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ALL required dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git build-essential bc libncurses5-dev libssl-dev \
            flex bison gperf python3 python3-pip python3-setuptools \
            zip unzip wget curl rsync ccache \
            xfonts-utils rdfind libparse-yapp-perl xsltproc \
            libxml-parser-perl patchutils lzop

      - name: Build CoreELEC Image
        run: |
          export USE_CCACHE=1
          export CCACHE_DIR=/tmp/ccache
          ccache -M 30G
          make -j4 image

      - name: Upload firmware from target folder
        uses: actions/upload-artifact@v4
        with:
          name: CoreELEC-AVDVPlus-Firmware
          path: target/*.tar
          retention-days: 7
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: CoreELEC-AVDVPlus-Firmware
          path: target/* # 上传target下所有文件（包含tar和img）
          retention-days: 7 # 保留7天
